version: '3'

volumes:
  static:
  esdata:

services:
  hellodjango_blog_tutorial:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: hellodjango_blog_tutorial
    container_name: hellodjango_blog_tutorial
    working_dir: /app
    restart: always
    volumes:
      - static:/app/static
    env_file:
      - .envs/.production
#    ports:
#      - "8000:8000"
    expose:
      - "8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    command: /start.sh
  db:
    image: daocloud.io/mysql:5.7
    environment:
      - MYSQL_DATABASE=my_blog # 数据库名称
      - MYSQL_ROOT_PASSWORD=123456a # 数据库密码
    volumes:
      - ./compose/production/mysql/data:/var/lib/mysql # 挂载数据库数据
      - ./compose/production/mysql/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: daocloud.io/redis:3
    command: redis-server
    volumes:
      - ./compose/production/redis:/data
    ports:
      - "6379:6379"
    restart: always # always表容器运行发生错误时一直重启
  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: hellodjango_blog_tutorial_nginx
    container_name: hellodjango_blog_tutorial_nginx
    volumes:
      - static:/apps/hellodjango_blog_tutorial/static
    ports:
      - "80:80"
      - "443:443"
    links:
      - hellodjango_blog_tutorial
    depends_on:
      - hellodjango_blog_tutorial
#    expose:
#      - "8000"
    restart: always
  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: hellodjango_blog_tutorial_elasticsearch
    container_name: hellodjango_blog_tutorial_elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    links:
      - hellodjango_blog_tutorial
    depends_on:
      - hellodjango_blog_tutorial
    restart: always