version: '3'

volumes:
  esdata:

services:
  blog:
    build:
      context: .
      dockerfile: compose/production/django/Dockerfile
    image: blog
    container_name: blog
    working_dir: /app
    command: /start.sh
    volumes:
      - .:/app
    env_file:
      - .envs/.production
    expose:
      - "8000"
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    restart: always
  db:
    image: daocloud.io/mysql:5.7
    container_name: db
    environment:
      - MYSQL_DATABASE=my_blog # 数据库名称
      - MYSQL_ROOT_PASSWORD=123456a # 数据库密码
    volumes:
      - ./compose/production/mysql/data:/var/lib/mysql # 挂载数据库数据
      - ./compose/production/mysql/conf/my.cnf:/etc/mysql/my.cnf
    ports:
      - "3306:3306"
    restart: always
  redis:
    image: daocloud.io/redis:3
    container_name: redis
    command: redis-server
    volumes:
      - ./compose/production/redis:/data
    ports:
      - "6379:6379"
    restart: always
  nginx:
    build:
      context: .
      dockerfile: compose/production/nginx/Dockerfile
    image: nginx
    container_name: nginx
    volumes:
      - ./static:/usr/share/nginx/html/static # 挂载静态文件
      - ./media:/usr/share/nginx/html/media # 挂载上传文件
      - ./compose/production/nginx/ssl:/usr/share/nginx/ssl # 挂载ssl证书目录
    ports:
      - "80:80"
      - "443:443"
    links:
      - blog
    depends_on:
      - blog
    restart: always
  elasticsearch:
    build:
      context: .
      dockerfile: ./compose/production/elasticsearch/Dockerfile
    image: elasticsearch
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
    links:
      - blog
    depends_on:
      - blog
    restart: always